# Generated by Django 4.1.5 on 2023-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create',
            field=models.DateTimeField(null=True),
        ),
    ]
