# Generated by Django 4.1.5 on 2023-02-03 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_test_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
